[versions]
agp = "8.2.0"
compose-bom = "2023.10.01"
compose-compiler = "1.5.7"
compose-multiplatform = "1.5.11"
kotlin = "1.9.21"

[libraries]
compose-activity = { group = "androidx.activity", name = "activity-compose", version = "1.8.2" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "compose-compiler" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }

[bundles]

[plugins]